### ISSUE TITLE
WordSwarm

### ISSUE THREAD

**Issue by felydl** [thisIsMikeKane/WordSwarm#1]
Hi Michael Kane! My name is Felicia De Lucia, i am a master's student.

I am working with Information Visualization and recently saw your project: WordSwarm, and it seems to me very great. I've downloaded the Python version that you have proposed in github.com and I’ve tried to use it. However, I have had some problems and I want to ask for your help to solve if it is possible. 

In step 6 I run python wordSwarm.py but when I do, I get this error: "No FreeType support compiled", I tried to solve it in every possible way without success.

I also want to know if instead of making scraping, my data is in a MySQL database, how should I do this?

I will appreciate any cooperation you can give me.

Thank you very much!

Regards.

**Comment by thisIsMikeKane** [comment]
This should be resolved if you follow the latest readme.
