### ISSUE TITLE
No FreeType support compiled

### ISSUE THREAD

**Issue by v-iashin** [thisIsMikeKane/WordSwarm#2]
`python wordSwarm.py -i nGramOut20140511205241.csv -s -m 15 -t "My First WordSwarm!"`

throws `No FreeType support compiled`

**Comment by thisIsMikeKane** [comment]
That error is being thrown from the PyGame code. Are you using the versions defined in this project's readme? I vaguely remember seeing this error once before, but forget how I fixed it. Check your versions against the readme and let me know.

**Comment by thisIsMikeKane** [comment]
This should be resolved if you follow the latest readme.
